# Generated by Django 4.2.7 on 2023-12-05 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/users/')),
                ('cover_image', models.ImageField(default='images/cover.jpg', null=True, upload_to='images/users/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('facebooklink', models.CharField(blank=True, max_length=20000, null=True)),
                ('twitterlink', models.CharField(blank=True, max_length=20000, null=True)),
                ('instagramlink', models.CharField(blank=True, max_length=20000, null=True)),
                ('youtubelink', models.CharField(blank=True, max_length=20000, null=True)),
                ('emaillink', models.CharField(blank=True, max_length=20000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
